sudo: required 

language: cpp

dist: trusty

services:   
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libprotobuf-dev protobuf-compiler libboost-all-dev

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "EhSojL5dZ7LY9S59Iixzw8KUtMqVdE8dZTZqZ0gnA1VfG4XcQr8u8Vi9jJzGaGxcXIL10p3nE4whrmhlEhUpxKkrcOgKo9vKmn9xByUHd0CBhBudZAdlQsq4DMEp20qAwg+5iuCUHS6cn3UjduQqdo9YMhfqFuRiH+U3oZxS0W4="

addons:
  coverity_scan:
    project:
      name: "noahdesu/zlog"
      description: "Build submitted via Travis CI"
    notification_email: noahwatkins@gmail.com
    build_command_prepend: "cmake ."
    build_command:   "make"
    branch_pattern: coverity_scan

script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then docker run -v $TRAVIS_BUILD_DIR:/src/zlog zlog/ci ; fi
