sudo: required 

language: cpp

dist: trusty

services:   
  - docker

matrix:
  include:
    - os: linux
      env: COVERAGE=1
    - os: linux
      env: COVERAGE=0

before_install:
  - sudo pip install cpp-coveralls

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "EhSojL5dZ7LY9S59Iixzw8KUtMqVdE8dZTZqZ0gnA1VfG4XcQr8u8Vi9jJzGaGxcXIL10p3nE4whrmhlEhUpxKkrcOgKo9vKmn9xByUHd0CBhBudZAdlQsq4DMEp20qAwg+5iuCUHS6cn3UjduQqdo9YMhfqFuRiH+U3oZxS0W4="

addons:
  apt:
    packages:
    - lcov
    - libboost-all-dev
    - libprotobuf-dev
    - protobuf-compiler
  coverity_scan:
    project:
      name: "noahdesu/zlog"
      description: "Build submitted via Travis CI"
    notification_email: noahwatkins@gmail.com
    build_command_prepend: "cmake ."
    build_command:   "make"
    branch_pattern: coverity_scan

script: ci/script.sh
after_success: ci/after_success.sh
